### ISSUE TITLE
Add smiley in Readme

### ISSUE THREAD

**Issue by praga4179** [praga4179/NavigationBar#10]

**Comment by pragapraga** [comment]
Shall I work on this? @praga4179

**Comment by ramyagr26** [comment]
Shall I work on this? @praga4179

**Comment by pragapraga** [comment]
Sorry I don't have the time to work on this please assign to someone else @praga4179

**Comment by praga4179** [comment]
@ramyag26 - Assigning to you , please work on this.

**Comment by praga4179** [comment]
Thanks @ramyagr26 for contributing and your efforts towards open source. Highly appreciate it
